CREATE TABLE IF NOT EXISTS fru_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id TEXT NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
    section TEXT NOT NULL,
    field TEXT NOT NULL,
    value TEXT,
    fetched_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
